@Transactions.Api_HostAddress = http://localhost:5243

### Crear transacción válida
POST {{Transactions.Api_HostAddress}}/transactions
Content-Type: application/json

{
  "sourceAccountId": "d36c99c1-18ee-49a7-b13a-bf79bdc013e1",
  "targetAccountId": "f20cf12c-d23a-41e2-93b2-2e5e9ae22458",
  "transferTypeId": 1,
  "value": 120
}

### Crear transacción que debe ser rechazada (valor > 2000)
POST {{Transactions.Api_HostAddress}}/transactions
Content-Type: application/json

{
  "sourceAccountId": "d36c99c1-18ee-49a7-b13a-bf79bdc013e1",
  "targetAccountId": "f20cf12c-d23a-41e2-93b2-2e5e9ae22458",
  "transferTypeId": 1,
  "value": 3000
}

### Consultar transacción por externalId (reemplaza {{externalId}})
GET {{Transactions.Api_HostAddress}}/transactions/{{externalId}}

